blank_issues_enabled: true
contact_links:
- name: Question
  url: 'https://github.com/roman-right/bunnet/discussions/new?category=question'
  about: Ask a question about how to use bunnet using github discussions

- name: Feature Request
  url: 'https://github.com/roman-right/bunnet/discussions/new?category=feature-request'
  about: >
    If you think we should add a new feature to bunnet, please start a discussion, once it attracts
    wider support, it can be migrated to an issue